### PR TITLE
fix: surface server errors in the ui [#122]

### LINKED ISSUE #122: Trying to add an email address already in use fails silently
### Steps to reproduce

1. Try to add an email address that is already in use in e.g. a different session
2. Watch it fail silently

### Expected results

It should show an explicatory error

### Actual results

It's silent

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by shinyford**
Resolves #122

### CODE REVIEW

File: packages/clerk_flutter/lib/src/widgets/organization/clerk_organization_list.dart [hunk 1]
```diff
@@ -46,13 +46,13 @@ class _ClerkOrganizationListState extends State<ClerkOrganizationList>
...
+    final actions = widget.actions ?? _defaultActions;
     return {
       'actions': actions.map((a) => a.label).join(';'),
     };
   }
 
-  List<ClerkUserAction> _defaultActions() {
+  late final List<ClerkUserAction> _defaultActions = () {
     final authState = ClerkAuth.of(context);
     final localizations = ClerkAuth.localizationsOf(context);
```
Comment (slightfoot) [inline packages/clerk_flutter/lib/src/widgets/organization/clerk_organization_list.dart:57]: cache AuthState and localizations

File: packages/clerk_flutter/lib/src/widgets/user/clerk_user_button.dart [hunk 2]
```diff
@@ -49,17 +49,17 @@ class _ClerkUserButtonState extends State<ClerkUserButton>
...
+        widget.additionalActions ?? _defaultAdditionalActions;
     return {
       'show_name': widget.showName,
       'session_actions': sessionActions.map((a) => a.label).join(';'),
       'additional_actions': additionalActions.map((a) => a.label).join(';'),
     };
   }
 
-  List<ClerkUserAction> _defaultSessionActions() {
+  late final List<ClerkUserAction> _defaultSessionActions = () {
```
Comment (slightfoot) [inline packages/clerk_flutter/lib/src/widgets/user/clerk_user_button.dart:62]: cache AuthState and localizations

**Review by slightfoot — CHANGES_REQUESTED** [review]
