### PR TITLE
fix: update user agent [#166]

### LINKED ISSUE #166: Update user agent for oauth webview
Facebook SSO is providing desktop UI in the webview, due to not understanding our bespoke UA. Google SSO requires the information in the bespoke UA though. This ticket is to find a UA that meets both criteria.

### LINKED ISSUE #167: Use English as default translation if none exist for current locale

### PR DESCRIPTION
**Pull request by shinyford**
Resolves #166

### CODE REVIEW

File: packages/clerk_auth/lib/src/clerk_constants.dart [hunk 1]
```diff
@@ -16,4 +16,10 @@ sealed class ClerkConstants {
 
   /// The url used to catch oauth redirects
   static const oauthRedirect = 'com.clerk.flutter://callback';
+
```
Comment (slightfoot) [inline packages/clerk_auth/lib/src/clerk_constants.dart:19]: Can't hard code this. We need to fetch the current user agent and prepend ours.

**Review by slightfoot — CHANGES_REQUESTED** [review]

**Review by slightfoot — APPROVED** [review]
