### PR TITLE
fix: regression introduced to pollforsessiontoken [#363]

### LINKED ISSUE #363: Regression in session token error handling
Via Jeremy from Clerk:

> Hi Clerk team — we think we’ve found a regression in the Flutter/Dart auth stack after upgrading to clerk_auth / clerk_flutter 0.0.14-beta.  In our app, transient transport failures during session-token polling (for example DNS / host lookup failures) are escaping from Auth._pollForSessionToken() as fatal errors instead of being converted into handled Clerk errors.  
> Why this is a problem:
> these are *normal transient network failures*, not true auth logic failures 
> they can happen while the app is backgrounded / offline / reconnecting 
> because the exception escapes from the SDK polling loop itself, we can’t reliably contain it at the app layer 
> in production, this turned into user-facing fatal crashes instead of recoverable auth degradation  
> 
> 
> Our reading is that 0.0.13-beta was more defensive here, and 0.0.14-beta changed behavior so raw transport exceptions can now escape the polling path.  As a temporary mitigation, we had to vendor a local hotfix of the package and patch _pollForSessionToken() so raw transport errors are converted back into handled ClerkErrors rather than crashing the app.  
> Two questions:
>  1. Is this a known issue / expected behavior change in 0.0.14-beta? 
> 2. Will this be addressed in an upcoming release, and if so, which version / timeframe should we watch for?

### PR DESCRIPTION
**Pull request by shinyford**
Resolves #363

### CODE REVIEW

File: packages/clerk_auth/test/unit/clerk_auth/auth_test.dart [hunk 1]
```diff
@@ -3294,7 +3294,11 @@ class _TestAuth extends Auth {
   final void Function(ClerkError) onError;
 
   @override
-  void handleError(ClerkError error) {
-    onError(error);
+  void handleError(Object error) {
+    if (error case ClerkError error) {
+      onError(error);
+    } else {
+      ClerkError.external(error);
```
Comment (slightfoot) [inline packages/clerk_auth/test/unit/clerk_auth/auth_test.dart]: I assume we want to send this new error to onError handler?
